#!/bin/bash

EXE="$(cd "$(dirname "${BASH_SOURCE:-$0}")"&& pwd)"
usage(){
	printf "__________________________________\nWelcome to FRESEAN V1.0!\nPlease refer to README.md for an\nin-depth guide to FRESEAN V1.0.\nQuick Guide of Available Programs\n----------------------------------\n\nfresean freqs: Generate list of available frequencies given\n\t\tcorrelaiton function length.\n\nfresean mtop: Generate custom .mtop topology.\n\nfresean coarse: Generate spatially coarsened trajectory.\n\nfresean covar: Generate frequency dependent cross-correlation\n\t\tmatrices.\n\nfresean eigen: Generate FRESEAN modes from velocity\n\t\tcross-correlation matrices.\n\nfresean extract: Extract vibrational modes from .mmat format\n\t\tinto .xyz format.\n\nfresean xyz2pdb: Convert .xyz modes to .pdb modes.\n\nfresean avg: Average over many velocity cross-correlation\n\t\tmatrices.\n\n-------------------------------------\nQuestions about repository should\nbe directed to: masauer2@asu.edu.\n-------------------------------------\n"
}

list_params_usage(){ printf "Error in user input:\nInvalid command-line options\nUsage: fresean freqs [-n <int>] [-t <float>] [-o <string>]\n" 1>&2; exit 1; }
parse_yml_usage(){ printf "Error in user input:\nInvalid command-line options\nUsage: fresean freqs [-n <int>] [-t <float>] [-o <string>]\n" 1>&2; exit 1; }

parse_yml_subcommand(){
    local OPTIND
    programname=$EXE/parse_yaml
    while getopts "f:" opt
    do
        case $opt in 
        	f) f=${OPTARG};;
        esac
    done
    if [ -z "$f" ]; then
        parse_yml_usage
        exit 1
    fi
    $programname ${f}
}

list_params_subcommand(){
	local OPTIND
	programname=$EXE/list_params
	echo $programname
	while getopts "f:" opt
	do
		case $opt in 
			f) f=${OPTARG};;
		esac
	done
	if [ -z "$f" ]; then
		list_params_usage
		exit 1
	fi
	$programname ${f}
}

case "$1" in
	list_params)
		list_params_subcommand "${@:2}";;
    parse_yml)
		parse_yml_subcommand "${@:2}";;
	*) 
		usage;;
esac
